# Generated by Django 3.2.9 on 2022-04-05 11:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('data_dir', models.CharField(editable=False, max_length=2048, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTypeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=1024, unique=True)),
                ('display_name', models.CharField(max_length=2048)),
                ('parameters', models.JSONField(null=True)),
                ('class_path', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(null=True)),
                ('inputs', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None)),
                ('job_id', models.CharField(max_length=128, null=True)),
                ('job_status', models.CharField(default='idle', max_length=16)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024, null=True), null=True, size=None)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tasktypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FilePathModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('path', models.CharField(editable=False, max_length=2048, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasetmodel')),
            ],
        ),
    ]
