[tool.briefcase]
project_name = "Mosamatic"
bundle = "com.rbeesoft"
icon = "src/mosamatic/resources/letter-m"
version = "1.3"
url = "https://mosamatic.rbeesoft.nl/wordpress/"
author = "Ralph Brecheisen"
author_email = "ralph.brecheisen@gmail.com"

[tool.briefcase.license]
file = "LICENSE"

[tool.briefcase.app.mosamatic]
formal_name = "Mosamatic"
description = "Tool for body composition analysis"
long_description = ""
console_app = true
sources = [
    "src/mosamatic",
    "src/models.py",
]
test_sources = [
    "tests",
]
requires = [
    "django",
    "django-jinja",
    "django-session-security",
    "django-guardian",
    "django-crispy-forms",
    "crispy-bootstrap5",
    "pendulum",
    "numpy",
    "pandas",
    "openpyxl",
    "scipy",
    "pillow",
    "pydicom",
    "dicom2nifti",
    "python-gdcm",
    "tensorflow==2.15.0",
    "torch",
    "torchvision",
    "torchsummary",
    "opencv-python",
    "totalsegmentator",
]
test_requires = [
    "pytest",
    "pytest-django",
]

[tool.briefcase.app.mosamatic.macOS]
universal_build = false
requires = []

[tool.briefcase.app.mosamatic.linux]
requires = []

[tool.briefcase.app.mosamatic.linux.system.debian]
system_requires = []
system_runtime_requires = []

[tool.briefcase.app.mosamatic.linux.system.rhel]
system_requires = []
system_runtime_requires = []

[tool.briefcase.app.mosamatic.linux.system.suse]
system_requires = []
system_runtime_requires = []

[tool.briefcase.app.mosamatic.linux.system.arch]
system_requires = []
system_runtime_requires = []

[tool.briefcase.app.mosamatic.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "24.08"
flatpak_sdk = "org.freedesktop.Sdk"

[tool.briefcase.app.mosamatic.windows]
requires = []

[tool.briefcase.app.mosamatic.iOS]
supported = false

[tool.briefcase.app.mosamatic.android]
supported = false

[tool.briefcase.app.mosamatic.web]
supported = false
